name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install server dependencies
      run: |
        cd server
        npm install
        
    - name: Install client dependencies
      run: |
        cd client
        npm install
        
    - name: Build client
      run: |
        cd client
        npm run build
        
    - name: Test server scripts
      run: |
        cd server
        npm test
        
    - name: Test client scripts
      run: |
        cd client
        npm test
        
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Verify project structure
      run: |
        echo "=== Project Structure ==="
        ls -la
        echo "=== Client Structure ==="
        ls -la client/
        echo "=== Server Structure ==="
        ls -la server/
        
    - name: Check package files
      run: |
        echo "=== Server package.json ==="
        cat server/package.json
        echo "=== Client package.json ==="
        cat client/package.json
        
    - name: Verify no sensitive files
      run: |
        echo "Checking for sensitive files..."
        if [ -f "server/.env" ]; then
          echo "❌ WARNING: .env file found in server directory"
          exit 1
        fi
        if [ -f "client/.env" ]; then
          echo "❌ WARNING: .env file found in client directory"
          exit 1
        fi
        echo "✅ No sensitive files found" 